#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Jul 01, 2025 09:01:28 AM PDT  platform: Windows NT
from os import path
from os import chdir
import sys
base_dir = path.dirname(path.abspath(__file__))
_location = base_dir
chdir(base_dir)
sys.path.append(path.join(base_dir, "utils"))
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
from organize import sorter
import Org


_debug = False # False to eliminate debug printing from callback functions.
def main(*args):
    
    ind = _location.find("\\")
    ind = _location.find("\\", ind+1)
    ind = _location.find("\\", ind+1)
    starting_dir = _location[0:ind]
    
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    org = sorter(starting_dir, starting_dir)
    # global _top1, _w1
    # _top1 = tk.Toplevel(root)
    # _w1 = Org.OpenPage(org, _top1)
    # Creates a toplevel widget.
    global _top2, _w2
    _top2 = root
    _w2 = Org.Toplevel1(org, _top2)
    root.mainloop()

def save_and_proceed(*args):
    if _debug:
        print('Organize_support.def save_and_proceed')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()

if __name__ == '__main__':
    Org.start_up()




